config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :download, only: [:show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController

  RESOURCES = {
    resume: "/Galamay_Christian_Angel.docx"
  }

  def show
    resume = RESOURCES[params[:id].to_sym]
    if resume
      redirect_to resume
    else
      render nothing: true, status: '404'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
= render partial: "partials/header"

= render partial: "partials/about"

= render partial: "partials/resume"

= render partial: "partials/portfolio"

-#= render partial: "partials/call-to-action"

= render partial: "partials/testimonials"

= render partial: "partials/contacts"

= render partial: "partials/footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnlinePortfolio
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/partials/_about.html.haml
%section#about
  .row
    .three.columns
      .profile-pic
        = image_tag "profilepic.jpg"
    .nine.columns.main-col
      %h2 About Me
      %p
        I love learning! I take every opportunity as a chance to gain more knowledge. I am very hard working and enthusiastic. I love computers and games. I have been dedicating most of my time learning how to work around computers and softwares. I like experimenting with the knowledge that I have. Even if I have explored some areas in programming, I am still in it for more! You have knowledge to share? Please tell, I'll listen :)
      .row
        .columns.contact-details
          %h2 Contact Details
          %p.address
            %span Christian Angel Galamay
            %br
              %span
                908 Ma. Luisa Street
                %br
                  Sampaloc, Metro Manila
              %br
                %span 0906-949-0280
                %br
                  %span chrono0424@gmail.com
        .columns.download
          %p
            = link_to "  Download Resume", download_path(:resume), class: "btn btn-primary fa fa-download"
      / end row
    / end .main-col
/ About Section End

app/views/partials/_call-to-action.html.haml
%section#call-to-action
  .row
    .two.columns.header-col
      %h1
        %span Get Hosting.
    .seven.columns
      %h2
        %a{:href => "http://www.dreamhost.com/r.cgi?287326|STYLESHOUT"} Host This Template on Dreamhost.
      %p
        Looking for an awesome and reliable webhosting? Try
        = succeed "." do
          %a{:href => "http://www.dreamhost.com/r.cgi?287326|STYLESHOUT"}
            %span DreamHost
        Get
        %span $50 off
        when you sign up with the promocode
        = succeed "." do
          %span STYLESHOUT
        / Simply type the promocode in the box labeled “Promo Code” when placing your order.
    .three.columns.action
      %a.button{:href => "http://www.dreamhost.com/r.cgi?287326|STYLESHOUT"} Sign Up Now

app/views/partials/_contacts.html.haml
%section#contact
  .row.section-head
    .two.columns.header-col
      %h1
        %span Get In Touch.
    .ten.columns
      %p.lead
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
        eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam
        voluptatem quia voluptas sit aspernatur aut odit aut fugit.
  .row
    .eight.columns
      / form
      %form#contactForm{:action => "", :method => "post", :name => "contactForm"}
        %fieldset
          %div
            %label{:for => "contactName"}
              Name
              %span.required *
            %input#contactName{:name => "contactName", :size => "35", :type => "text", :value => ""}
          %div
            %label{:for => "contactEmail"}
              Email
              %span.required *
            %input#contactEmail{:name => "contactEmail", :size => "35", :type => "text", :value => ""}
          %div
            %label{:for => "contactSubject"} Subject
            %input#contactSubject{:name => "contactSubject", :size => "35", :type => "text", :value => ""}
          %div
            %label{:for => "contactMessage"}
              Message
              %span.required *
            %textarea#contactMessage{:cols => "50", :name => "contactMessage", :rows => "15"}
          %div
            %button.submit Submit
            %span#image-loader
              %img{:alt => "", :src => "images/loader.gif"}
      / Form End
      / contact-warning
      #message-warning Error boy
      / contact-success
      #message-success
        %i.fa.fa-check>
        Your message was sent, thank you!
        %br
    %aside.four.columns.footer-widgets
      .widget.widget_contact
        %h4 Address and Phone
        %p.address
          Christian Angel Galamay
          %br
            908 Ma. Luisa Street
            %br
              Sampaloc, Manila
              %br
                %span 0906-949-0280
      .widget.widget_tweets
        %h4.widget-title Latest Tweets
        %ul#twitter
          %li
            %span
              This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
              Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum
              %a{:href => "#"} http://t.co/CGIrdxIlI3
            %bgit
              %a{:href => "#"} 2 Days Ago
          %li
            %span
              Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam,
              eaque ipsa quae ab illo inventore veritatis et quasi
              %a{:href => "#"} http://t.co/CGIrdxIlI3
            %b
              %a{:href => "#"} 3 Days Ago
/ Contact Section End

app/views/partials/_footer.html.haml
%footer
  .row
    .twelve.columns
      %ul.social-links
        %li
          %a{:href => "https://www.facebook.com/christian.galamay", target: "blank"}
            %i.fa.fa-facebook
        %li
          %a{:href => "https://twitter.com/chrono0424", target: "blank"}
            %i.fa.fa-twitter
        %li
          %a{:href => "https://plus.google.com/u/1/108904045733182918607/posts", target: "blank"}
            %i.fa.fa-google-plus
        %li
          %a{:href => "https://www.linkedin.com/in/kian1213", target: "blank"}
            %i.fa.fa-linkedin
      %ul.copyright
        %li &copy; Copyright 2015 Christian Angel Galamay
    #go-top
      %a.smoothscroll{:href => "#home", :title => "Back to Top"}
        %i.icon-up-open

app/views/partials/_header.html.haml
%header#home
  %nav#nav-wrap
    %a.mobile-btn{:href => "#nav-wrap", :title => "Show navigation"} Show navigation
    %a.mobile-btn{:href => "#", :title => "Hide navigation"} Hide navigation
    %ul#nav.nav
      %li.current
        %a.smoothscroll{:href => "#home"} Home
      %li
        %a.smoothscroll{:href => "#about"} About
      %li
        %a.smoothscroll{:href => "#resume"} Resume
      %li
        %a.smoothscroll{:href => "#portfolio"} Works
      %li
        %a.smoothscroll{:href => "#testimonials"} Testimonials
      %li
        %a.smoothscroll{:href => "#contact"} Contact
  .row.banner
    .banner-text
      %h1.responsive-headline Hi! I'm Christian Angel
      %h3
        I'm a Manila based
        = succeed "," do
          %span Web Developer
        using Ruby on Rails as my primary tool
        on developing projects. You can
        %a.smoothscroll{:href => "#about"} start scrolling
        and learn more
        = succeed "." do
          %a.smoothscroll{:href => "#about"} about me
      %hr/
      %ul.social
        %li
          %a{:href => "https://www.facebook.com/christian.galamay", target: "blank"}
            %i.fa.fa-facebook
        %li
          %a{:href => "https://twitter.com/chrono0424", target: "blank"}
            %i.fa.fa-twitter
        %li
          %a{:href => "https://plus.google.com/u/1/108904045733182918607/posts", target: "blank"}
            %i.fa.fa-google-plus
        %li
          %a{:href => "https://www.linkedin.com/in/kian1213", target: "blank"}
            %i.fa.fa-linkedin
  %p.scrolldown
    %a.smoothscroll{:href => "#about"}
      %i.icon-down-circle

app/views/partials/_portfolio.html.haml
%section#portfolio
  .row
    .twelve.columns.collapsed
      %h1 For Portfolio part ,, Samples only (Pending.. TODO).
      / portfolio-wrapper
      #portfolio-wrapper.bgrid-quarters.s-bgrid-thirds.cf
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-01", :title => ""}
              = image_tag "portfolio/coffee.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Coffee
                  %p Illustrration
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-02", :title => ""}
              = image_tag "portfolio/console.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Console
                  %p Web Development
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-03", :title => ""}
              = image_tag "portfolio/judah.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Judah
                  %p Webdesign
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-04", :title => ""}
              = image_tag "portfolio/into-the-light.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Into The Light
                  %p Photography
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-05", :title => ""}
              = image_tag "portfolio/farmerboy.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Farmer Boy
                  %p Branding
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-06", :title => ""}
              = image_tag "portfolio/girl.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Girl
                  %p Photography
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-07", :title => ""}
              = image_tag "portfolio/origami.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Origami
                  %p Illustrration
              .link-icon
                %i.icon-plus
        / item end
        .columns.portfolio-item
          .item-wrap
            %a{:href => "#modal-08", :title => ""}
              = image_tag "portfolio/retrocam.jpg"
              .overlay
                .portfolio-item-meta
                  %h5 Retrocam
                  %p Web Development
              .link-icon
                %i.icon-plus
        / item end
      / portfolio-wrapper end
    / twelve columns end
    /
      Modal Popup
      \---------------------------------------------------------------
    #modal-01.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-coffee.jpg')}"}/
      .description-box
        %h4 Coffee Cup
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Branding, Webdesign
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-01 End
    #modal-02.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-console.jpg')}"}/
      .description-box
        %h4 Console
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Branding, Web Development
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-02 End
    #modal-03.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-judah.jpg')}"}/
      .description-box
        %h4 Judah
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Branding
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-03 End
    #modal-04.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-intothelight.jpg')}"}/
      .description-box
        %h4 Into the Light
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Photography
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-04 End
    #modal-05.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-farmerboy.jpg')}"}/
      .description-box
        %h4 Farmer Boy
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Branding, Webdesign
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-05 End
    #modal-06.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-girl.jpg')}"}/
      .description-box
        %h4 Girl
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Photography
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-06 End
    #modal-07.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-origami.jpg')}"}/
      .description-box
        %h4 Origami
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Branding, Illustration
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-07 End
    #modal-08.popup-modal.mfp-hide
      %img.scale-with-grid{:alt => "", :src => "#{image_path('portfolio/modals/m-retrocam.jpg')}"}/
      .description-box
        %h4 Retrocam
        %p Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit.
        %span.categories
          %i.fa.fa-tag>
          Webdesign, Photography
      .link-box
        %a{:href => "http://www.behance.net"} Details
        %a.popup-modal-dismiss Close
    / modal-01 End
  / row End
/ Portfolio Section End

app/views/partials/_resume.html.haml
%section#resume
  /
    Education
    \-----------------------------------------------
  .row.education
    .three.columns.header-col
      %h1
        %span Education
    .nine.columns.main-col
      .row.item
        .twelve.columns
          %h3 St.Matthew of Blumentritt Institure of Technology
          %p.info
            Information Technology
            %span &bull;
            %em.date March 2013
          %p
            I studied here as an IT student, I learn the basics of coding, thanks to my mentors :). Lorem ipsum, still on progress what to put, 
      / item end
    -#
      .row.item
        .twelve.columns
          %h3 School of Cool Designers
          %p.info
            B.A. Degree in Graphic Design
            %span &bull;
            %em.date March 2003
          %p
            This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
            Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem
            nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan
            ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non  mauris vitae erat
      / item end
    / main-col end
  / End Education
  /
    Work
    \-----------------------------------------------
  .row.work
    .three.columns.header-col
      %h1
        %span Work
    .nine.columns.main-col
      .row.item
        .twelve.columns
          %h3 Redtonic Solutions
          %p.info
            Ruby on Rails Developer
            %span &bull;
            %em.date June 2015 - Present
          %p
            Work with a team, using Ruby on Rails as our programming tool. We create web applications as well as integration of bootstrap template to rails app.
          %p
            Lorem ipsum,, more additional infos soon :)
      / item end
      .row.item
        .twelve.columns
          %h3 Information Mangers
          %p.info
            Junior Application Developer
            %span &bull;
            %em.date May 2013 - June 2015
          %p
            My first job as a programmer. We maintain big business application for clients, doing additional request and additional features.
          %p
            Lorem ipsum dolor set amet,, more info soon
      / item end
    / main-col end
  / End Work
  /
    Skills
    \-----------------------------------------------
  .row.skill
    .three.columns.header-col
      %h1
        %span Skills
    .nine.columns.main-col
      %p
        Below are list of my skills and ... lorem ipsum more txt to come
      .bars
        %ul.skills
          %li
            %span.bar-expand.ruby
            %em Ruby on Rails
          %li
            %span.bar-expand.html5
            %em HTML5
          %li
            %span.bar-expand.css3
            %em CSS3
          %li
            %span.bar-expand.jquery
            %em Jquery
          %li
            %span.bar-expand.coffee
            %em Coffeescript
          %li
            %span.bar-expand.react
            %em ReactJs
      / end skill-bars
    / main-col end
  / End skills
/ Resume Section End

app/views/partials/_testimonials.html.haml
%section#testimonials
  .text-container
    .row
      .two.columns.header-col
        %h1
          %span Client Testimonials
      .ten.columns.flex-container
        .flexslider
          %ul.slides
            %li
              %blockquote
                %p
                  Your work is going to fill a large part of your life, and the only way to be truly satisfied is
                  to do what you believe is great work. And the only way to do great work is to love what you do.
                  If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.
                %cite Lorem ipsum
            / slide ends
            %li
              %blockquote
                %p
                  This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
                  Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem
                  nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.
                %cite Lorem Dolor
            / slide ends
        / div.flexslider ends
      / div.flex-container ends
    / row ends
  / text-container ends
/ Testimonials Section End